-- =====================================================
-- Redgum Shire Council: events (6.x) + outdoor (3.11, 3.12)
-- =====================================================
-- GENERATED by scripts/genRedgumEventsOutdoor.ts. Do not hand-edit, regenerate.
--
-- The original Redgum seed only emitted yes-no-unsure answers, so every
-- module built on single-select questions was invisible in the demo. Those
-- are exactly the modules a council recognises, so the gap showed.
--
-- Single-select and multi-select answers live in module_responses
-- .multi_select_values as a JSON array (one element for single-select),
-- which is the shape the app reads back.
--
-- Events map to the festival site, outdoor and playground to the gardens.
-- Idempotent: each module deletes its own rows before re-inserting.
-- =====================================================
do $$
declare
  v_org uuid; v_user uuid; v_site uuid;
begin
  select id into v_org from organisations where name ilike '%shire council%' order by created_at limit 1;
  if v_org is null then raise exception 'Redgum council org not found - run redgum_demo_seed.sql first.'; end if;
  select user_id into v_user from organisation_memberships where organisation_id = v_org order by created_at limit 1;

  -- 6.1 Event planning and promotion -> Riverbend Summer Festival
  select id into v_site from sites where organisation_id = v_org and name = 'Riverbend Summer Festival';
  delete from module_responses where session_id = 'seed-redgum-6-1';
  delete from module_progress where organisation_id = v_org and module_id = '6.1'
    and coalesce(site_id::text,'-') = coalesce(v_site::text,'-');
  insert into module_progress (session_id, module_id, module_code, status, confidence_snapshot, summary,
    started_at, completed_at, organisation_id, site_id, user_id, last_modified_by_user_id)
  values ('seed-redgum-6-1','6.1','6.1','completed','mixed','{"doingWell":["Accessibility is raised at the event scoping stage, not after the program is set.","An accessibility budget line exists for the main festival program."],"priorityActions":[{"questionId":"6.1-PC-1","questionText":"Has accessibility been considered in the early planning stages of this event?","action":"Apply the same access planning to every event in the program, including the smaller pop-up and satellite events.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.1-PC-2","questionText":"Does your event promotion include accessibility information?","action":"Publish access information on every event page, not only the festival landing page.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.1-D-2","questionText":"Have people with disability been consulted in planning this event?","action":"Involve people with disability in planning the program, not only in feedback gathered after the event.","priority":"medium","timeframe":"30-90 days"}],"areasToExplore":["Whether event leads know who to ask when an access request arrives late.","How access requirements captured at registration reach the on-site team."],"professionalReview":[]}'::jsonb, now() - interval '53 days', now() - interval '49 days', v_org, v_site, v_user, v_user);
  insert into module_responses (session_id, module_id, question_id, answer, notes, partial_description, multi_select_values, organisation_id, site_id, user_id) values
    ('seed-redgum-6-1','6.1','6.1-PC-1',null,null,null,'["not-yet"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-PC-2',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-PC-3',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-PC-4',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-PC-5',null,null,null,'["unknown"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-1',null,null,null,'["yes-dedicated"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-2',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-3',null,null,null,'["dietary"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-4',null,null,null,'["large-print"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-5',null,null,null,'["no-deadline"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-6',null,null,null,'["yes-concession"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-7',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-8',null,null,null,'["not-considered"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-9',null,null,null,'["informal"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-10',null,null,null,'["yes-proactive"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-11',null,null,null,'["yes-intentional"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-D-12',null,null,null,'["general-contact"]',v_org,v_site,v_user),
    ('seed-redgum-6-1','6.1','6.1-OTHER',null,'Council is preparing an access plan template that every event lead completes at the scoping stage.',null,null,v_org,v_site,v_user);

  -- 6.2 Venue and physical access -> Riverbend Summer Festival
  select id into v_site from sites where organisation_id = v_org and name = 'Riverbend Summer Festival';
  delete from module_responses where session_id = 'seed-redgum-6-2';
  delete from module_progress where organisation_id = v_org and module_id = '6.2'
    and coalesce(site_id::text,'-') = coalesce(v_site::text,'-');
  insert into module_progress (session_id, module_id, module_code, status, confidence_snapshot, summary,
    started_at, completed_at, organisation_id, site_id, user_id, last_modified_by_user_id)
  values ('seed-redgum-6-2','6.2','6.2','completed','strong','{"doingWell":["A step-free route runs from accessible parking to the main stage.","Accessible toilets are distributed across the site rather than clustered at one end.","Wheelchair viewing areas are provided at the main stage with a companion seat beside them."],"priorityActions":[{"questionId":"6.2-D-15","questionText":"Are accessible pathway surfaces provided for outdoor or temporary venues?","action":"Seal or matt the gravel approach to the riverside stage so the accessible route is continuous across the whole site.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.2-D-8","questionText":"Are trip hazards managed, including cable covers and secure wiring?","action":"Keep the accessible path of travel clear of cabling, signage and food queues once the site is built.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.2-D-19","questionText":"Are accessible drop-off and pick-up areas clearly marked and actively managed?","action":"Add a second accessible drop-off closer to the eastern entry, and actively manage it during peak arrival.","priority":"medium","timeframe":"30-90 days"}],"areasToExplore":["Whether temporary infrastructure narrows the accessible route once vendors are in place.","How the site holds up after rain on the unsealed sections."],"professionalReview":[]}'::jsonb, now() - interval '54 days', now() - interval '50 days', v_org, v_site, v_user, v_user);
  insert into module_responses (session_id, module_id, question_id, answer, notes, partial_description, multi_select_values, organisation_id, site_id, user_id) values
    ('seed-redgum-6-2','6.2','6.2-PC-1',null,null,null,'["yes-mostly"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-PC-2',null,null,null,'["dropoff-only"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-PC-3',null,null,null,'["nearby"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-PC-4',null,null,null,'["front-rows","aisle-access","flexible"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-PC-5',null,null,null,'["yes-dedicated"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-1',null,null,null,'["yes-team"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-2',null,null,null,'["floor-level"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-3',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-4',null,null,null,'["maps","parking","none"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-5',null,null,null,'["yes-all-hard"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-6',null,null,null,'["phone-booking"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-7',null,null,null,'["designated-area"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-8',null,null,null,'["yes-comprehensive"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-9',null,null,null,'["yes-in-accessible"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-10',null,null,null,'["yes-contrasting"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-11',null,null,null,'["yes-staffed"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-12',null,null,null,'["yes-basic"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-13',null,null,null,'["not-addressed"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-14',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-15',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-16',null,null,null,'["na"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-17',null,null,null,'["on-request"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-18',null,null,null,'["not-assessed"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-D-19',null,null,null,'["yes-managed"]',v_org,v_site,v_user),
    ('seed-redgum-6-2','6.2','6.2-OTHER',null,'The site plan is reviewed with an access consultant each year before the layout is locked.',null,null,v_org,v_site,v_user);

  -- 6.3 Communication and information -> Riverbend Summer Festival
  select id into v_site from sites where organisation_id = v_org and name = 'Riverbend Summer Festival';
  delete from module_responses where session_id = 'seed-redgum-6-3';
  delete from module_progress where organisation_id = v_org and module_id = '6.3'
    and coalesce(site_id::text,'-') = coalesce(v_site::text,'-');
  insert into module_progress (session_id, module_id, module_code, status, confidence_snapshot, summary,
    started_at, completed_at, organisation_id, site_id, user_id, last_modified_by_user_id)
  values ('seed-redgum-6-3','6.3','6.3','completed','mixed','{"doingWell":["An access guide is published ahead of the festival.","Key event information is offered in more than one format."],"priorityActions":[{"questionId":"6.3-PC-2","questionText":"Is event information available in accessible formats?","action":"Publish the access guide in plain language and Easy Read when tickets go on sale, so people can decide before they book.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.3-D-3","questionText":"Is there a sensory map or guide for the event?","action":"Produce a sensory map for the site showing the loud zones, the quiet spaces and the calmest times of day.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.3-D-5","questionText":"How will you communicate program changes or delays?","action":"Set out how program changes and delays will reach people who cannot hear an announcement over the PA.","priority":"medium","timeframe":"30-90 days"}],"areasToExplore":["Whether the access guide is written in plain language and available in Easy Read.","How last-minute program changes reach people who rely on the published access information."],"professionalReview":[]}'::jsonb, now() - interval '55 days', now() - interval '51 days', v_org, v_site, v_user, v_user);
  insert into module_responses (session_id, module_id, question_id, answer, notes, partial_description, multi_select_values, organisation_id, site_id, user_id) values
    ('seed-redgum-6-3','6.3','6.3-PC-1',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-PC-2',null,null,null,'["qr-codes"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-PC-3',null,null,null,'["app-notifications"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-PC-4',null,null,null,'["yes-accessible"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-1',null,null,null,'["considered"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-2',null,null,null,'["handrails","textured-surfaces","relying-on-venue"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-3',null,null,null,'["yes-detailed"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-4',null,null,null,'["yes-basic"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-5',null,null,null,'["staff-notify","info-desk","visual-screens"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-6',null,null,null,'["tablets-apps","pen-paper","picture-menus"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-7',null,null,null,'["floor-mic","seated-option","roving"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-8',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-9',null,null,null,'["optional"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-10',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-D-11',null,null,null,'["vendor-claims"]',v_org,v_site,v_user),
    ('seed-redgum-6-3','6.3','6.3-OTHER',null,'We publish the access guide four weeks out so people can plan before tickets are released.',null,null,v_org,v_site,v_user);

  -- 6.4 Sensory access and technology -> Riverbend Summer Festival
  select id into v_site from sites where organisation_id = v_org and name = 'Riverbend Summer Festival';
  delete from module_responses where session_id = 'seed-redgum-6-4';
  delete from module_progress where organisation_id = v_org and module_id = '6.4'
    and coalesce(site_id::text,'-') = coalesce(v_site::text,'-');
  insert into module_progress (session_id, module_id, module_code, status, confidence_snapshot, summary,
    started_at, completed_at, organisation_id, site_id, user_id, last_modified_by_user_id)
  values ('seed-redgum-6-4','6.4','6.4','completed','needs-work','{"doingWell":["A hearing loop is available in the main marquee."],"priorityActions":[{"questionId":"6.4-PC-1","questionText":"What hearing access services will be available at the event?","action":"Extend hearing augmentation beyond the main marquee to the other staged venues, and test it before doors open at each one.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.4-PC-3","questionText":"Are there sensory considerations for neurodivergent attendees?","action":"Provide a quiet or low-sensory space with clear signage and a staff member who knows where it is.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.4-D-7","questionText":"Are there warnings for sensory triggers (strobe lights, loud noises, special effects)?","action":"Publish warnings for strobe lighting, loud passages and special effects ahead of the event, not only at the door.","priority":"high","timeframe":"30-90 days"}],"areasToExplore":["Whether the hired hearing loops are tested on site rather than assumed to work.","What sensory information people ask for most often when they contact the festival."],"professionalReview":[]}'::jsonb, now() - interval '56 days', now() - interval '52 days', v_org, v_site, v_user, v_user);
  insert into module_responses (session_id, module_id, question_id, answer, notes, partial_description, multi_select_values, organisation_id, site_id, user_id) values
    ('seed-redgum-6-4','6.4','6.4-PC-1',null,null,null,'["hearing-loop","assistive-listening"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-PC-2',null,null,null,'["audio-description","large-print"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-PC-3',null,null,null,'["sensory-kits"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-1',null,null,null,'["to-be-confirmed"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-2',null,null,null,'["tbc"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-3',null,null,null,'["tested-compliant"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-4',null,null,null,'["live-ad"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-5',null,null,null,'["byod"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-6',null,null,null,'["yes-cushions"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-7',null,null,null,'["no-warnings"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-8',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-9',null,null,null,'["sensory-vests"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-10',null,null,null,'["policy-requested"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-11',null,null,null,'["warnings-only"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-D-12',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-4','6.4','6.4-OTHER',null,'Portable hearing loops are hired each year. Owning a set is in the next budget bid.',null,null,v_org,v_site,v_user);

  -- 6.5 On-the-day operations -> Riverbend Summer Festival
  select id into v_site from sites where organisation_id = v_org and name = 'Riverbend Summer Festival';
  delete from module_responses where session_id = 'seed-redgum-6-5';
  delete from module_progress where organisation_id = v_org and module_id = '6.5'
    and coalesce(site_id::text,'-') = coalesce(v_site::text,'-');
  insert into module_progress (session_id, module_id, module_code, status, confidence_snapshot, summary,
    started_at, completed_at, organisation_id, site_id, user_id, last_modified_by_user_id)
  values ('seed-redgum-6-5','6.5','6.5','completed','mixed','{"doingWell":["A staffed access hub operates beside the main entrance for the duration of the festival.","Accessible facilities are signed and kept clear during the event."],"priorityActions":[{"questionId":"6.5-PC-1","questionText":"Do staff and volunteers receive disability awareness training?","action":"Bring casual volunteers into the access briefing, since many start on the day and currently miss it.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.5-D-1","questionText":"Who is responsible for accessibility on the day?","action":"Name one person as accountable for access on each day of the festival, and put that name on the run sheet.","priority":"high","timeframe":"30-90 days"},{"questionId":"6.5-D-4","questionText":"How will you handle late accessibility requests on the day?","action":"Agree in advance how a late access request on the day is handled, and who can authorise it.","priority":"medium","timeframe":"30-90 days"}],"areasToExplore":["How access issues raised during the event are recorded and carried into next year.","Whether the access hub is findable from the far end of the site."],"professionalReview":[]}'::jsonb, now() - interval '57 days', now() - interval '53 days', v_org, v_site, v_user, v_user);
  insert into module_responses (session_id, module_id, question_id, answer, notes, partial_description, multi_select_values, organisation_id, site_id, user_id) values
    ('seed-redgum-6-5','6.5','6.5-PC-1',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-PC-2',null,null,null,'["no-queues"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-PC-3',null,null,null,'["none-specific","accessible-counters","dietary-labelled"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-PC-4',null,null,null,'["relief-area","water-available","staff-aware"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-PC-5',null,null,null,'["not-yet-developed"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-1',null,null,null,'["not-assigned"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-2',null,null,null,'["no-specific","on-day-desk"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-3',null,null,null,'["mobility-aids","sensory-kits"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-4',null,null,null,'["no-process"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-5',null,null,null,'["yes-dedicated"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-6',null,null,null,'["yes-debrief"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-7',null,null,null,'["general-accessible"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-8',null,null,null,'["standard-only"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-9',null,null,null,'["yes-planned"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-10',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-11',null,null,null,'["no-reentry"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-12',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-13',null,null,null,'["mobility-equipment"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-14',null,null,null,'["cleaning"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-15',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-16',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-D-17',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-6-5','6.5','6.5-OTHER',null,'A staffed access hub sits beside the main entrance for the duration of the festival.',null,null,v_org,v_site,v_user);

  -- 3.11 Outdoor spaces and grounds -> Botanic Gardens & Playground
  select id into v_site from sites where organisation_id = v_org and name = 'Botanic Gardens & Playground';
  delete from module_responses where session_id = 'seed-redgum-3-11';
  delete from module_progress where organisation_id = v_org and module_id = '3.11'
    and coalesce(site_id::text,'-') = coalesce(v_site::text,'-');
  insert into module_progress (session_id, module_id, module_code, status, confidence_snapshot, summary,
    started_at, completed_at, organisation_id, site_id, user_id, last_modified_by_user_id)
  values ('seed-redgum-3-11','3.11','3.11','completed','mixed','{"doingWell":["The main circuit is sealed, level and wide enough for two-way passing.","Seating with armrests is provided at intervals along the main circuit.","Accessible parking sits close to the main entry."],"priorityActions":[{"questionId":"3.11-PC-1","questionText":"Are outdoor paths and walkways firm, level and wide enough for a person using a wheelchair or mobility aid?","action":"Upgrade the secondary tracks from loose gravel to a firm compacted surface, or publish clearly which routes are accessible.","priority":"high","timeframe":"30-90 days"},{"questionId":"3.11-D-2","questionText":"Are rest areas with seating provided at regular intervals along outdoor paths?","action":"Add rest areas with seating and shade at regular intervals on the longer sections of the main circuit.","priority":"medium","timeframe":"30-90 days"},{"questionId":"3.11-D-13","questionText":"Is accessible information provided about outdoor areas, such as trail maps, audio guides or QR codes linking to digital content?","action":"Publish a grounds access map showing surface types, gradients and the location of seating and toilets.","priority":"medium","timeframe":"30-90 days"}],"areasToExplore":["Whether path widths are maintained as planting grows through the season.","How the grounds are checked for surface damage after winter."],"professionalReview":[]}'::jsonb, now() - interval '79 days', now() - interval '75 days', v_org, v_site, v_user, v_user);
  insert into module_responses (session_id, module_id, question_id, answer, notes, partial_description, multi_select_values, organisation_id, site_id, user_id) values
    ('seed-redgum-3-11','3.11','3.11-PC-1',null,null,'The main circuit is sealed and accessible; the secondary tracks are compacted gravel.','["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-PC-2',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-PC-3',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-PC-4',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-PC-5',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-PC-6',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-1',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-2',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-3',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-4',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-5',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-6',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-7',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-8',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-9',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-10',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-11',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-12',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-13',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-D-14',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-11','3.11','3.11-OTHER',null,'A path condition audit is scheduled after each winter to catch surface damage early.',null,null,v_org,v_site,v_user);

  -- 3.12 Playgrounds and play spaces -> Botanic Gardens & Playground
  select id into v_site from sites where organisation_id = v_org and name = 'Botanic Gardens & Playground';
  delete from module_responses where session_id = 'seed-redgum-3-12';
  delete from module_progress where organisation_id = v_org and module_id = '3.12'
    and coalesce(site_id::text,'-') = coalesce(v_site::text,'-');
  insert into module_progress (session_id, module_id, module_code, status, confidence_snapshot, summary,
    started_at, completed_at, organisation_id, site_id, user_id, last_modified_by_user_id)
  values ('seed-redgum-3-12','3.12','3.12','completed','strong','{"doingWell":["The playground was co-designed with families through the Disability Advisory Committee.","An accessible path connects parking, toilets and the play space.","The play space includes equipment usable by children who use mobility aids.","Fencing and gates allow a carer to manage a child who may wander."],"priorityActions":[{"questionId":"3.12-PC-2","questionText":"Is the playground surface firm and level enough for wheelchair or mobility aid access to reach play equipment?","action":"Extend the accessible ground surface beyond the entry and main equipment to the whole play space.","priority":"high","timeframe":"30-90 days"},{"questionId":"3.12-D-2","questionText":"Is there a quiet zone or calm space near the playground for children who become overstimulated?","action":"Add a quiet zone near the playground for children who become overstimulated.","priority":"medium","timeframe":"30-90 days"},{"questionId":"3.12-PC-7","questionText":"Are supporting facilities (toilets, drinking water, bins) accessible and located near the playground?","action":"Bring the supporting facilities up to standard: an accessible toilet, drinking water and bins within easy reach of the play space.","priority":"medium","timeframe":"30-90 days"}],"areasToExplore":["Whether shade covers the equipment most used by children who cannot self-regulate temperature.","How families find out what the playground offers before they travel."],"professionalReview":[]}'::jsonb, now() - interval '80 days', now() - interval '76 days', v_org, v_site, v_user, v_user);
  insert into module_responses (session_id, module_id, question_id, answer, notes, partial_description, multi_select_values, organisation_id, site_id, user_id) values
    ('seed-redgum-3-12','3.12','3.12-PC-1',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-PC-2',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-PC-3',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-PC-4',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-PC-5',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-PC-6',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-PC-7',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-1',null,null,null,'["yes"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-2',null,null,'The ground surface is compliant at the entry and under the main equipment, not across the whole space.','["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-3',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-4',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-5',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-6',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-7',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-8',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-9',null,null,null,'["partially"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-10',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-11',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-D-12',null,null,null,'["no"]',v_org,v_site,v_user),
    ('seed-redgum-3-12','3.12','3.12-OTHER',null,'The playground was co-designed with families through the Disability Advisory Committee.',null,null,v_org,v_site,v_user);

  raise notice 'Seeded events (6.1-6.5) and outdoor (3.11, 3.12) for Redgum Shire Council.';
end $$;
