/**
 * Access Statement generator
 *
 * Turns an organisation's module responses into a customer-facing Access Profile:
 * a grouped list of accessibility features the venue HAS. Per product decision,
 * only Yes and Partial features render. "No" and unanswered features are omitted
 * so nothing reads as a failing on the venue.
 */

import type { ModuleProgress, QuestionResponse } from '../hooks/useModuleProgress';
import { accessModules } from '../data/accessModules';
import { ACCESS_STATEMENT_CATEGORIES, type FeatureDef } from '../data/accessStatementFeatures';

export interface StatementFeature {
  label: string;
  state: 'yes' | 'partial';
  detail?: string;
  /** Set by applyOverrides so the edit UI can target a generated feature. */
  refKey?: string;
  /** Set by applyOverrides for a user-added custom feature. */
  customId?: string;
}

export interface StatementCategory {
  id: string;
  title: string;
  features: StatementFeature[];
}

export interface AccessStatement {
  organisationName: string;
  generatedAt: string;
  categories: StatementCategory[];
  featureCount: number;
}

/** questionId -> (optionId -> label), so present features can name the option matched. */
function buildOptionLabelIndex(): Map<string, Map<string, string>> {
  const index = new Map<string, Map<string, string>>();
  for (const mod of accessModules) {
    for (const q of mod.questions) {
      if (!q.options || q.options.length === 0) continue;
      const opts = new Map<string, string>();
      for (const opt of q.options) opts.set(opt.id, opt.label);
      index.set(q.id, opts);
    }
  }
  return index;
}

function resolveFeature(
  def: FeatureDef,
  responseByQuestion: Map<string, QuestionResponse>,
  optionLabels: Map<string, Map<string, string>>,
): StatementFeature | null {
  let present = false;
  let partial = false;
  let partialDetail: string | undefined;
  const matchedLabels: string[] = [];

  for (const qid of def.yesNo ?? []) {
    const r = responseByQuestion.get(qid);
    if (!r) continue;
    if (r.answer === 'yes') present = true;
    else if (r.answer === 'partially') {
      partial = true;
      if (!partialDetail) partialDetail = r.partialDescription?.trim() || r.notes?.trim() || undefined;
    }
  }

  for (const match of def.options ?? []) {
    const values = responseByQuestion.get(match.questionId)?.multiSelectValues ?? [];
    const hits = match.anyOf.filter((id) => values.includes(id));
    if (hits.length > 0) {
      present = true;
      for (const id of hits) {
        const label = optionLabels.get(match.questionId)?.get(id);
        if (label) matchedLabels.push(label);
      }
    }
  }

  for (const qid of def.yesOption ?? []) {
    const values = responseByQuestion.get(qid)?.multiSelectValues ?? [];
    if (values.some((v) => /^yes/i.test(v))) present = true;
    else if (values.some((v) => /partial|limited|request|some/i.test(v))) partial = true;
  }

  if (present) {
    const detail = Array.from(new Set(matchedLabels)).slice(0, 2).join(', ') || undefined;
    return { label: def.label, state: 'yes', detail };
  }
  if (partial) return { label: def.label, state: 'partial', detail: partialDetail };
  return null;
}

export function generateAccessStatement(
  progress: Record<string, ModuleProgress>,
  organisationName: string,
): AccessStatement {
  const responseByQuestion = new Map<string, QuestionResponse>();
  for (const mod of Object.values(progress)) {
    for (const r of mod.responses ?? []) responseByQuestion.set(r.questionId, r);
  }

  const optionLabels = buildOptionLabelIndex();
  const categories: StatementCategory[] = [];
  let featureCount = 0;

  for (const cat of ACCESS_STATEMENT_CATEGORIES) {
    const features: StatementFeature[] = [];
    for (const def of cat.features) {
      const feature = resolveFeature(def, responseByQuestion, optionLabels);
      if (feature) features.push(feature);
    }
    if (features.length > 0) {
      categories.push({ id: cat.id, title: cat.title, features });
      featureCount += features.length;
    }
  }

  return {
    organisationName,
    generatedAt: new Date().toISOString(),
    categories,
    featureCount,
  };
}

export function serializeAccessStatementText(statement: AccessStatement): string {
  const date = new Date(statement.generatedAt).toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
  let out = `${statement.organisationName}\nAccessibility profile\nSelf-reported as of ${date}\n${'='.repeat(40)}\n`;
  for (const cat of statement.categories) {
    out += `\n${cat.title}\n`;
    for (const f of cat.features) {
      out += `  ${f.state === 'yes' ? 'Yes' : 'Partial'} - ${f.label}${f.detail ? ` (${f.detail})` : ''}\n`;
    }
  }
  out += '\nGenerated by Access Compass.';
  return out;
}
