/**
 * PDF Report Generator
 *
 * Generates professionally formatted PDF reports using jsPDF.
 * Includes headers, footers, page numbers, and proper formatting.
 */

import jsPDF from 'jspdf';
import type { Report } from '../hooks/useReportGeneration';

// Colors
const COLORS = {
  primary: '#1a1a2e',
  purple: '#7c3aed',
  orange: '#e67700',
  green: '#22c55e',
  red: '#ef4444',
  gray: '#6b7280',
  lightGray: '#f3f4f6',
};

// Page dimensions (A4)
const PAGE = {
  width: 210,
  height: 297,
  marginLeft: 20,
  marginRight: 20,
  marginTop: 25,
  marginBottom: 25,
  contentWidth: 170, // 210 - 20 - 20
};

interface PDFGeneratorOptions {
  report: Report;
  includeCoverPage?: boolean;
  includeTableOfContents?: boolean;
}

/**
 * Generate a professional PDF report
 */
export function generatePDFReport(options: PDFGeneratorOptions): jsPDF {
  const { report, includeCoverPage = true, includeTableOfContents = true } = options;
  const doc = new jsPDF('p', 'mm', 'a4');

  let currentPage = 1;
  let yPosition = PAGE.marginTop;

  // Helper: Add header to current page
  const addHeader = () => {
    doc.setFillColor(26, 26, 46); // primary color
    doc.rect(0, 0, PAGE.width, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Access Compass - Accessibility Self-Review Report', PAGE.marginLeft, 10);
    doc.text(report.organisation, PAGE.width - PAGE.marginRight, 10, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  };

  // Helper: Add footer to current page
  const addFooter = () => {
    const footerY = PAGE.height - 10;

    // Footer line
    doc.setDrawColor(200, 200, 200);
    doc.line(PAGE.marginLeft, footerY - 5, PAGE.width - PAGE.marginRight, footerY - 5);

    // Footer text
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128); // gray
    doc.text('Generated by Access Compass by Flare Access', PAGE.marginLeft, footerY);
    doc.text(
      new Date(report.generatedAt).toLocaleDateString('en-AU', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      }),
      PAGE.width / 2,
      footerY,
      { align: 'center' }
    );
    doc.text(`Page ${currentPage}`, PAGE.width - PAGE.marginRight, footerY, { align: 'right' });

    doc.setTextColor(0, 0, 0);
  };

  // Helper: Add new page
  const addNewPage = () => {
    doc.addPage();
    currentPage++;
    yPosition = PAGE.marginTop;
    addHeader();
  };

  // Helper: Check if we need a new page
  const checkNewPage = (neededHeight: number) => {
    if (yPosition + neededHeight > PAGE.height - PAGE.marginBottom) {
      addFooter();
      addNewPage();
      return true;
    }
    return false;
  };

  // Helper: Add section title
  const addSectionTitle = (title: string, color: string = COLORS.primary) => {
    checkNewPage(15);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(color);
    doc.text(title, PAGE.marginLeft, yPosition);
    yPosition += 8;

    // Underline
    doc.setDrawColor(color);
    doc.setLineWidth(0.5);
    doc.line(PAGE.marginLeft, yPosition, PAGE.marginLeft + 40, yPosition);
    yPosition += 8;

    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
  };

  // Helper: Add paragraph text with word wrapping
  const addParagraph = (text: string, fontSize: number = 10) => {
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, PAGE.contentWidth);
    const lineHeight = fontSize * 0.4;

    for (const line of lines) {
      checkNewPage(lineHeight + 2);
      doc.text(line, PAGE.marginLeft, yPosition);
      yPosition += lineHeight + 1;
    }
    yPosition += 3;
  };

  // Helper: Add bullet list
  const addBulletList = (items: string[], bulletColor: string = COLORS.gray) => {
    doc.setFontSize(10);
    const lineHeight = 5;

    for (const item of items) {
      const lines = doc.splitTextToSize(item, PAGE.contentWidth - 8);
      const totalHeight = lines.length * lineHeight + 2;

      checkNewPage(totalHeight);

      // Bullet
      doc.setFillColor(bulletColor);
      doc.circle(PAGE.marginLeft + 2, yPosition - 1.5, 1.2, 'F');

      // Text
      doc.setTextColor(0, 0, 0);
      for (let i = 0; i < lines.length; i++) {
        doc.text(lines[i], PAGE.marginLeft + 8, yPosition);
        yPosition += lineHeight;
      }
      yPosition += 1;
    }
    yPosition += 3;
  };

  // Helper: Add stat box
  const addStatBox = (
    x: number,
    y: number,
    width: number,
    value: string,
    label: string,
    bgColor: string
  ) => {
    // Background
    doc.setFillColor(bgColor);
    doc.roundedRect(x, y, width, 25, 3, 3, 'F');

    // Value
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(value, x + width / 2, y + 12, { align: 'center' });

    // Label
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(label, x + width / 2, y + 20, { align: 'center' });

    doc.setTextColor(0, 0, 0);
  };

  // ============================================
  // COVER PAGE
  // ============================================
  if (includeCoverPage) {
    // Background gradient effect (simplified)
    doc.setFillColor(26, 26, 46);
    doc.rect(0, 0, PAGE.width, PAGE.height, 'F');

    // Decorative accent
    doc.setFillColor(124, 58, 237);
    doc.rect(0, PAGE.height * 0.4, PAGE.width, 3, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(32);
    doc.setFont('helvetica', 'bold');
    doc.text('Accessibility', PAGE.width / 2, PAGE.height * 0.3, { align: 'center' });
    doc.text('Self-Review Report', PAGE.width / 2, PAGE.height * 0.3 + 14, { align: 'center' });

    // Subtitle
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(200, 200, 200);
    const reportTypeText =
      report.reportType === 'pulse-check' ? 'Pulse Check Summary' : 'Deep Dive Assessment';
    doc.text(reportTypeText, PAGE.width / 2, PAGE.height * 0.5, { align: 'center' });

    // Organisation name
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(124, 58, 237);
    doc.text(report.organisation, PAGE.width / 2, PAGE.height * 0.6, { align: 'center' });

    // Generated date
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated: ${new Date(report.generatedAt).toLocaleDateString('en-AU', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      })}`,
      PAGE.width / 2,
      PAGE.height * 0.65,
      { align: 'center' }
    );

    // Branding
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text('Access Compass', PAGE.width / 2, PAGE.height * 0.85, { align: 'center' });
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('by Flare Access', PAGE.width / 2, PAGE.height * 0.88, { align: 'center' });

    // Start new page for content
    addNewPage();
  } else {
    addHeader();
  }

  // ============================================
  // TABLE OF CONTENTS (Deep Dive only)
  // ============================================
  if (includeTableOfContents && report.reportType === 'deep-dive') {
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.primary);
    doc.text('Table of Contents', PAGE.marginLeft, yPosition);
    yPosition += 15;

    const tocItems = [
      'Executive Summary',
      'Modules Reviewed',
      report.urlAnalysisResults?.length ? 'Website Accessibility Analysis' : null,
      report.mediaAnalysisResults?.length ? 'Media Analysis Results' : null,
      "What's Going Well",
      'Priority Actions',
      report.quickWins?.length ? 'Quick Wins' : null,
      'Areas to Explore',
      'Detailed Findings',
      'Suggested Next Steps',
      'Professional Support',
      'Disclaimer',
    ].filter(Boolean) as string[];

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);

    tocItems.forEach((item, index) => {
      doc.text(`${index + 1}. ${item}`, PAGE.marginLeft + 5, yPosition);
      yPosition += 7;
    });

    addFooter();
    addNewPage();
  }

  // ============================================
  // EXECUTIVE SUMMARY
  // ============================================
  addSectionTitle('Executive Summary');

  // Stats boxes
  const boxWidth = 38;
  const boxGap = 5;
  const startX = PAGE.marginLeft;

  checkNewPage(35);

  addStatBox(
    startX,
    yPosition,
    boxWidth,
    String(report.executiveSummary.modulesCompleted),
    'Modules Completed',
    '#1a1a2e'
  );
  addStatBox(
    startX + boxWidth + boxGap,
    yPosition,
    boxWidth,
    String(report.executiveSummary.strengthsCount),
    'Strengths',
    '#22c55e'
  );
  addStatBox(
    startX + (boxWidth + boxGap) * 2,
    yPosition,
    boxWidth,
    String(report.executiveSummary.actionsCount),
    'Priority Actions',
    '#ef4444'
  );
  addStatBox(
    startX + (boxWidth + boxGap) * 3,
    yPosition,
    boxWidth,
    String(report.executiveSummary.areasToExploreCount),
    'Areas to Explore',
    '#fbbf24'
  );

  yPosition += 35;

  // Completion progress
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Overall Completion: ${report.executiveSummary.completionPercentage}%`,
    PAGE.marginLeft,
    yPosition
  );
  yPosition += 5;

  // Progress bar
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(PAGE.marginLeft, yPosition, PAGE.contentWidth, 6, 2, 2, 'F');
  doc.setFillColor(124, 58, 237);
  doc.roundedRect(
    PAGE.marginLeft,
    yPosition,
    (PAGE.contentWidth * report.executiveSummary.completionPercentage) / 100,
    6,
    2,
    2,
    'F'
  );
  yPosition += 15;

  // ============================================
  // MODULES REVIEWED
  // ============================================
  if (report.moduleEvidence && report.moduleEvidence.length > 0) {
    addSectionTitle('Modules Reviewed');

    report.moduleEvidence.forEach((evidence) => {
      checkNewPage(25);

      // Module card background
      doc.setFillColor(248, 248, 252);
      doc.roundedRect(PAGE.marginLeft, yPosition - 2, PAGE.contentWidth, 20, 2, 2, 'F');

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`${evidence.moduleCode} - ${evidence.moduleName}`, PAGE.marginLeft + 5, yPosition + 5);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(COLORS.gray);

      let metaText = '';
      if (evidence.completedAt) {
        metaText += `Completed: ${new Date(evidence.completedAt).toLocaleDateString('en-AU')}`;
      }
      if (evidence.completedBy) {
        metaText += metaText ? ' | ' : '';
        metaText += `By: ${evidence.completedBy}`;
        if (evidence.completedByRole) {
          metaText += ` (${evidence.completedByRole})`;
        }
      }
      if (metaText) {
        doc.text(metaText, PAGE.marginLeft + 5, yPosition + 12);
      }

      doc.setTextColor(COLORS.green);
      doc.text(`${evidence.strengthsCount} strengths`, PAGE.width - PAGE.marginRight - 50, yPosition + 5);
      doc.setTextColor(COLORS.red);
      doc.text(`${evidence.actionsCount} actions`, PAGE.width - PAGE.marginRight - 50, yPosition + 12);

      doc.setTextColor(0, 0, 0);
      yPosition += 25;
    });
    yPosition += 5;
  }

  // ============================================
  // URL ANALYSIS RESULTS
  // ============================================
  if (report.urlAnalysisResults && report.urlAnalysisResults.length > 0) {
    addSectionTitle('Website Accessibility Analysis');

    report.urlAnalysisResults.forEach((analysis) => {
      checkNewPage(40);

      // URL and score
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(COLORS.purple);
      doc.text(analysis.url, PAGE.marginLeft, yPosition);
      yPosition += 5;

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      doc.text(`Score: ${analysis.overallScore}/100 (${analysis.overallStatus})`, PAGE.marginLeft, yPosition);
      yPosition += 6;

      addParagraph(analysis.summary, 9);

      if (analysis.strengths.length > 0) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('Strengths:', PAGE.marginLeft, yPosition);
        yPosition += 4;
        doc.setFont('helvetica', 'normal');
        addBulletList(analysis.strengths, COLORS.green);
      }

      if (analysis.improvements.length > 0) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('Areas for Improvement:', PAGE.marginLeft, yPosition);
        yPosition += 4;
        doc.setFont('helvetica', 'normal');
        addBulletList(analysis.improvements, COLORS.orange);
      }
    });
  }

  // ============================================
  // MEDIA ANALYSIS RESULTS
  // ============================================
  if (report.mediaAnalysisResults && report.mediaAnalysisResults.length > 0) {
    addSectionTitle('Media Analysis Results');

    report.mediaAnalysisResults.forEach((analysis) => {
      checkNewPage(35);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      const title = analysis.fileName || analysis.url || formatAnalysisType(analysis.analysisType);
      doc.text(`${formatAnalysisType(analysis.analysisType)}: ${title}`, PAGE.marginLeft, yPosition);
      yPosition += 5;

      doc.setFont('helvetica', 'normal');
      doc.text(`Score: ${analysis.overallScore}/100 (${analysis.overallStatus})`, PAGE.marginLeft, yPosition);
      yPosition += 6;

      addParagraph(analysis.summary, 9);

      if (analysis.strengths.length > 0) {
        addBulletList(analysis.strengths.slice(0, 3), COLORS.green);
      }

      if (analysis.improvements.length > 0) {
        addBulletList(analysis.improvements.slice(0, 3), COLORS.orange);
      }
    });
  }

  // ============================================
  // WHAT'S GOING WELL
  // ============================================
  if (report.sections.strengths.content.length > 0) {
    addSectionTitle("What's Going Well", COLORS.green);
    addBulletList(report.sections.strengths.content as string[], COLORS.green);
  }

  // ============================================
  // PRIORITY ACTIONS
  // ============================================
  if (report.sections.priorityActions.content.length > 0) {
    addSectionTitle('Priority Actions', COLORS.red);
    addBulletList(report.sections.priorityActions.content as string[], COLORS.red);
  }

  // ============================================
  // QUICK WINS
  // ============================================
  if (report.quickWins && report.quickWins.length > 0) {
    addSectionTitle('Quick Wins', COLORS.purple);
    addParagraph(
      'These actions offer significant accessibility improvements with minimal effort:',
      9
    );

    report.quickWins.forEach((win) => {
      checkNewPage(20);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`${win.title}`, PAGE.marginLeft, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(COLORS.gray);
      doc.text(`(${win.effort} effort, ${win.impact} impact)`, PAGE.marginLeft + 80, yPosition);
      doc.setTextColor(0, 0, 0);
      yPosition += 5;
      addParagraph(win.description, 9);
    });
  }

  // ============================================
  // AREAS TO EXPLORE
  // ============================================
  if (report.sections.areasToExplore.content.length > 0) {
    addSectionTitle('Areas to Explore', COLORS.orange);
    addBulletList(report.sections.areasToExplore.content as string[], COLORS.orange);
  }

  // ============================================
  // DETAILED FINDINGS (Deep Dive only)
  // ============================================
  if (report.reportType === 'deep-dive' && report.detailedFindings && report.detailedFindings.length > 0) {
    addSectionTitle('Detailed Findings');

    report.detailedFindings.forEach((finding) => {
      checkNewPage(15);

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(COLORS.primary);
      doc.text(finding.moduleName, PAGE.marginLeft, yPosition);
      yPosition += 8;
      doc.setTextColor(0, 0, 0);

      finding.issues.forEach((issue) => {
        checkNewPage(30);

        // Issue header
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(issue.questionText, PAGE.marginLeft + 5, yPosition, {
          maxWidth: PAGE.contentWidth - 30,
        });

        // Priority badge
        const priorityColor =
          issue.priority === 'high' ? COLORS.red : issue.priority === 'medium' ? COLORS.orange : COLORS.gray;
        doc.setFillColor(priorityColor);
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(7);
        doc.roundedRect(PAGE.width - PAGE.marginRight - 25, yPosition - 3, 20, 6, 1, 1, 'F');
        doc.text(`${issue.priority}`, PAGE.width - PAGE.marginRight - 15, yPosition + 1, {
          align: 'center',
        });
        doc.setTextColor(0, 0, 0);
        yPosition += 8;

        // Reasoning
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        addParagraph(issue.reasoning, 9);

        // Recommended actions
        if (issue.recommendedActions.length > 0) {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(9);
          doc.text('Recommended Actions:', PAGE.marginLeft + 5, yPosition);
          yPosition += 4;
          doc.setFont('helvetica', 'normal');
          addBulletList(
            issue.recommendedActions.map((a) => a),
            COLORS.purple
          );
        }

        yPosition += 3;
      });
    });
  }

  // ============================================
  // SUGGESTED NEXT STEPS
  // ============================================
  addSectionTitle('Suggested Next Steps');

  // Two columns
  checkNewPage(40);
  const colWidth = (PAGE.contentWidth - 10) / 2;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Things you can explore now', PAGE.marginLeft, yPosition);
  doc.text('Things to plan for later', PAGE.marginLeft + colWidth + 10, yPosition);
  yPosition += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  const maxItems = Math.max(report.nextSteps.exploreNow.length, report.nextSteps.planForLater.length);

  for (let i = 0; i < maxItems; i++) {
    checkNewPage(6);

    if (i < report.nextSteps.exploreNow.length) {
      doc.setFillColor(COLORS.green);
      doc.circle(PAGE.marginLeft + 2, yPosition - 1, 1, 'F');
      const lines = doc.splitTextToSize(report.nextSteps.exploreNow[i], colWidth - 8);
      doc.text(lines[0], PAGE.marginLeft + 6, yPosition);
    }

    if (i < report.nextSteps.planForLater.length) {
      doc.setFillColor(COLORS.purple);
      doc.circle(PAGE.marginLeft + colWidth + 12, yPosition - 1, 1, 'F');
      const lines = doc.splitTextToSize(report.nextSteps.planForLater[i], colWidth - 8);
      doc.text(lines[0], PAGE.marginLeft + colWidth + 16, yPosition);
    }

    yPosition += 6;
  }
  yPosition += 5;

  // ============================================
  // PROFESSIONAL SUPPORT
  // ============================================
  addSectionTitle('When Professional Support May Help', COLORS.purple);

  addParagraph('Based on your self-review, you may benefit from professional advice if:');

  const detectedIndicators = report.professionalSupport.indicators.filter((i) => i.detected);
  if (detectedIndicators.length > 0) {
    addBulletList(
      detectedIndicators.map((i) => `${i.category}: ${i.reason}`),
      COLORS.purple
    );
  }

  if (report.professionalSupport.recommended) {
    checkNewPage(15);
    doc.setFillColor(248, 240, 252);
    doc.roundedRect(PAGE.marginLeft, yPosition, PAGE.contentWidth, 12, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.purple);
    doc.text(
      'Based on your responses, we recommend considering professional support.',
      PAGE.marginLeft + 5,
      yPosition + 7
    );
    doc.setTextColor(0, 0, 0);
    yPosition += 18;
  }

  addParagraph(
    "This self-review is designed to support learning and planning. Seeking professional advice doesn't mean you've failed - it's a normal next step for many organisations.",
    9
  );

  // ============================================
  // DISCLAIMER
  // ============================================
  addSectionTitle('Important Disclaimer', COLORS.orange);

  checkNewPage(30);
  doc.setFillColor(255, 251, 235);
  doc.roundedRect(PAGE.marginLeft, yPosition, PAGE.contentWidth, 35, 2, 2, 'F');
  doc.setDrawColor(COLORS.orange);
  doc.setLineWidth(0.5);
  doc.roundedRect(PAGE.marginLeft, yPosition, PAGE.contentWidth, 35, 2, 2, 'S');

  yPosition += 5;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  const disclaimerLines = doc.splitTextToSize(
    'This guidance is for information only. It is not legal advice, a compliance certificate, or a substitute for professional accessibility auditing. Actions are suggestions based on your responses. This review is indicative only and based on self-reported information. It does not verify accuracy or confirm compliance with accessibility standards or legal requirements.',
    PAGE.contentWidth - 10
  );

  disclaimerLines.forEach((line: string) => {
    doc.text(line, PAGE.marginLeft + 5, yPosition);
    yPosition += 4;
  });

  // Add final footer
  addFooter();

  return doc;
}

/**
 * Download the PDF report
 */
export function downloadPDFReport(report: Report): void {
  const doc = generatePDFReport({ report });
  const fileName = `${report.organisation.replace(/[^a-z0-9]/gi, '-')}-accessibility-report-${
    new Date().toISOString().split('T')[0]
  }.pdf`;
  doc.save(fileName);
}

// Helper function to format analysis type
function formatAnalysisType(analysisType: string): string {
  const labels: Record<string, string> = {
    menu: 'Menu',
    brochure: 'Brochure',
    flyer: 'Flyer',
    'large-print': 'Large Print',
    signage: 'Signage',
    lighting: 'Lighting',
    'ground-surface': 'Ground Surface',
    pathway: 'Pathway',
    entrance: 'Entrance',
    ramp: 'Ramp',
    stairs: 'Stairs',
    door: 'Door',
    'social-media-post': 'Social Media Post',
    'social-media-url': 'Social Media Profile',
    'website-wave': 'Website Audit',
  };
  return labels[analysisType] || analysisType;
}
