import type { DIAPItem } from '../hooks/useDIAPManagement';
import type { ModuleProgress } from '../hooks/useModuleProgress';

export function generateDIAPProgressSummary(items: DIAPItem[], orgName: string): string {
  const total = items.length;
  const byStatus = {
    'not-started': items.filter(i => i.status === 'not-started').length,
    'in-progress': items.filter(i => i.status === 'in-progress').length,
    'achieved': items.filter(i => i.status === 'achieved').length,
    'ongoing': items.filter(i => i.status === 'ongoing').length,
    'on-hold': items.filter(i => i.status === 'on-hold').length,
    'cancelled': items.filter(i => i.status === 'cancelled').length,
  };
  const highPriority = items.filter(i => i.priority === 'high' && i.status !== 'achieved' && i.status !== 'cancelled');

  let summary = `ACCESS COMPASS - DIAP Progress Summary
Organisation: ${orgName}
Date: ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}
${'='.repeat(50)}

TOTAL ITEMS: ${total}
  Not started: ${byStatus['not-started']}
  In progress: ${byStatus['in-progress']}
  Achieved: ${byStatus['achieved']}
  Ongoing: ${byStatus['ongoing']}
  On hold: ${byStatus['on-hold']}
  Cancelled: ${byStatus['cancelled']}
`;

  if (highPriority.length > 0) {
    summary += `\nHIGH PRIORITY OUTSTANDING (${highPriority.length}):\n`;
    highPriority.forEach(item => {
      summary += `  - ${item.objective}`;
      if (item.responsibleRole) summary += ` (${item.responsibleRole})`;
      if (item.dueDate) summary += ` [Due: ${new Date(item.dueDate).toLocaleDateString('en-AU')}]`;
      summary += '\n';
    });
  }

  summary += '\nGenerated by Access Compass.';
  return summary;
}

export function generateOverallProgressSummary(
  progress: Record<string, ModuleProgress>,
  totalModules: number,
  orgName: string
): string {
  const entries = Object.values(progress);
  const completed = entries.filter(p => p.status === 'completed').length;
  const inProgress = entries.filter(p => p.status === 'in-progress').length;
  const notStarted = totalModules - completed - inProgress;
  const percentage = totalModules > 0 ? Math.round((completed / totalModules) * 100) : 0;

  let summary = `ACCESS COMPASS - Progress Summary
Organisation: ${orgName}
Date: ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}
${'='.repeat(50)}

OVERALL: ${completed}/${totalModules} modules completed (${percentage}%)
  Completed: ${completed}
  In progress: ${inProgress}
  Not started: ${notStarted}
`;

  const completedModules = entries.filter(p => p.status === 'completed');
  if (completedModules.length > 0) {
    summary += '\nCOMPLETED MODULES:\n';
    completedModules.forEach(p => {
      const doingWell = p.summary?.doingWell?.length || 0;
      const actions = p.summary?.priorityActions?.length || 0;
      summary += `  - ${p.moduleCode}: ${doingWell} doing well, ${actions} actions\n`;
    });
  }

  summary += '\nGenerated by Access Compass.';
  return summary;
}

export function downloadAsText(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
